config/routes.rb
Rails.application.routes.draw do
  resources :lists
  resources :recipes
  resources :recipes_steps
  resources :ingredients
  resources :garnishes
  resources :categories
  resources :glasses

  resources :recipe_steps do
    post :sort, on: :collection
  end

  get 'sync' => 'sync#index'

  root to: 'visitors#index'
  devise_for :users
  resources :users

  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for "User", at: 'auth'
    end
  end

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sync' => 'sync#create'
      end
    end
  end

end

app/models/garnish.rb
class Garnish < ActiveRecord::Base
  after_update :after_update_model
  after_create :after_create_model
  after_destroy :after_destroy_model
  has_many :garnishes_recipes
  has_many :garnishes, through: :garnishes_recipes, :dependent => :destroy

  private
  
  def after_update_model
    vh = VersionHistory.new
    vh.table_name = self.class.to_s.pluralize
    vh.action = 'UPDATE'
    vh.primary_keys = "id:#{self.id}"
    vh.change_fields = "name:#{self.name}"
    vh.save!
  end

  def after_create_model
    vh = VersionHistory.new
    vh.table_name = self.class.to_s.pluralize
    vh.action = 'CREATE'
    vh.primary_keys = "id:#{self.id}"
    vh.change_fields = "name:#{self.name}"
    vh.save!
  end

  def after_destroy_model
    vh = VersionHistory.new
    vh.table_name = self.class.to_s.pluralize
    vh.action = 'DELETE'
    vh.primary_keys = "id:#{self.id}"
    vh.save!
  end
end

app/controllers/garnishes_controller.rb
class GarnishesController < ApplicationController
  before_action :set_garnish, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  # GET /garnishes
  # GET /garnishes.json
  def index
    @garnishes = Garnish.where("LOWER(name) like ?", "%#{params[:q] ? params[:q].downcase : ''}%").paginate(:page => params[:page], :per_page => 198).order(:name)
    respond_to do |format|
        format.html
        format.json {render :json => @garnishes.map(&:attributes)}
    end
  end

  # GET /garnishes/1
  # GET /garnishes/1.json
  def show
  end

  # GET /garnishes/new
  def new
    @garnish = Garnish.new
  end

  # GET /garnishes/1/edit
  def edit
  end

  # POST /garnishes
  # POST /garnishes.json
  def create
    @garnish = Garnish.new(garnish_params)

    respond_to do |format|
      if @garnish.save
        format.html { redirect_to garnishes_url, notice: 'Garnish was successfully created.' }
        format.json { render :show, status: :created, location: @garnish }
      else
        format.html { render :new }
        format.json { render json: @garnish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /garnishes/1
  # PATCH/PUT /garnishes/1.json
  def update
    respond_to do |format|
      if @garnish.update(garnish_params)
        format.html { redirect_to garnishes_url, notice: 'Garnish was successfully updated.' }
        format.json { render :show, status: :ok, location: @garnish }
      else
        format.html { render :edit }
        format.json { render json: @garnish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /garnishes/1
  # DELETE /garnishes/1.json
  def destroy
    @garnish.destroy
    respond_to do |format|
      format.html { redirect_to garnishes_url, notice: 'Garnish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garnish
      @garnish = Garnish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def garnish_params
      params.require(:garnish).permit(:name)
    end

  private
  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end
end

app/helpers/garnishes_helper.rb
module GarnishesHelper
end

app/views/garnishes/_form.html.erb
<div class="col-xs-12">
  <div class="form-center">
    
    <%= form_for @garnish , html: {class: "form-horizontal form-edit"} do |f| %>
      <% if @garnish.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@garnish.errors.count, "error") %> prohibited this garnish from being saved:</h2>

          <ul>
          <% @garnish.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      
         <div class="form-group">
          <%= f.label :name, 'New Name:', class:'control-label col-xs-2'  %>
          <div class="col-xs-10">
            <%= f.text_field :name, class:'form-control'  %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-xs-12">
              <%= f.submit :class => "btn btn-default" %>    
              <%= link_to 'Back', garnishes_path, :class => "btn btn-default" %>
            </div>
        </div>
    <% end %>    
  </div>
</div>

app/views/garnishes/edit.html.erb
<div class="title col-xs-12">
	<h1>Editing Garnish <span><%= @garnish.name%><span></h1>
</div>
<%= render 'form' %>

app/views/garnishes/index.html.erb
<!-- p id="notice"><%= notice %></p-->

<div class="title col-xs-12">
  <h1>GARNISHES</h1>
  <div class="col-xs-12 links">
    <%= link_to 'New Garnish', new_garnish_path %>
  </div>
  
</div>

<div class="col-xs-12">
  <div class="container">
    <div class="row">
      <% @garnishes.each do |garnish| %>
      <div class="col-xs-4">
        <h3> <%= garnish.name %></h3>
        <p><%= link_to 'Edit', edit_garnish_path(garnish) %> - <%= link_to 'Delete', garnish, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      </div>
      <% end %>
  </div>
</div>

<div class="pagination col-xs-12">
  <%= will_paginate(@garnishes) %>
</div>

<%= form_tag garnishes_path, :method => :get do %>
  <%= content_tag :label do %>
    Search name:
    <%= text_field_tag :q, params[:q] %>
    <%= hidden_field_tag :page, 1 %>
  <% end %>
<% end %>

app/views/garnishes/new.html.erb
<div class="title col-xs-12">
	<h1>New Garnish</h1>
</div>


<%= render 'form' %>

app/views/garnishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @garnish.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>