config/routes.rb
Rails.application.routes.draw do
  resources :lists
  resources :recipes
  resources :recipes_steps
  resources :ingredients
  resources :garnishes
  resources :categories
  resources :glasses

  resources :recipe_steps do
    post :sort, on: :collection
  end

  get 'sync' => 'sync#index'

  root to: 'visitors#index'
  devise_for :users
  resources :users

  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for "User", at: 'auth'
    end
  end

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sync' => 'sync#create'
      end
    end
  end

end

app/controllers/glasses_controller.rb
class GlassesController < ApplicationController
  before_action :set_glass, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :admin_only, :except => :show


  # GET /glasses
  # GET /glasses.json
  def index
    @glasses = Glass.where("LOWER(name) like ?", "%#{params[:q] ? params[:q].downcase : ''}%").paginate(:page => params[:page], :per_page => 198).order(:name)
  end

  # GET /glasses/1
  # GET /glasses/1.json
  def show
  end

  # GET /glasses/new
  def new
    @glass = Glass.new
  end

  # GET /glasses/1/edit
  def edit
  end

  # POST /glasses
  # POST /glasses.json
  def create
    @glass = Glass.new(glass_params)


    respond_to do |format|
      if @glass.save
        format.html { redirect_to glasses_url, notice: 'Glass was successfully created.' }
        format.json { render :show, status: :created, location: @glass }
      else
        format.html { render :new }
        format.json { render json: @glass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /glasses/1
  # PATCH/PUT /glasses/1.json
  def update
    respond_to do |format|
      if @glass.update(glass_params)
        format.html { redirect_to glasses_url, notice: 'Glass was successfully updated.' }
        format.json { render :show, status: :ok, location: @glass }
      else
        format.html { render :edit }
        format.json { render json: @glass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /glasses/1
  # DELETE /glasses/1.json
  def destroy
    
    respond_to do |format|
      if @glass.destroy
        format.html { redirect_to glasses_url, notice: @glass.flash_notice }
      else
        format.html { redirect_to glasses_url, alert: @glass.flash_notice }
      end
        format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_glass
      @glass = Glass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def glass_params
      params.require(:glass).permit(:name, :image_url)
    end

  private
  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  

  
  

end

app/helpers/glasses_helper.rb
module GlassesHelper
end

app/views/glasses/_form.html.erb
<div class="col-xs-12">
  <div class="form-center">
    
    <%= form_for @glass , html: {multipart: true, class: "form-horizontal form-edit"} do |f| %>
      <% if @glass.errors.any? %>
        <div id="error_explanation" class="col-xs-offset-4 col-xs-8">
          <h2><%= pluralize(@glass.errors.count, "error") %> prohibited this glass from being saved:</h2>

          <ul>
          <% @glass.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>


         <div class="form-group">
          <%= f.label :name, 'New Name:', class:'control-label col-xs-2'  %>
          <div class="col-xs-10">
            <%= f.text_field :name, class:'form-control'  %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :name, 'Image:', class:'control-label col-xs-2'  %>
          <div class="col-xs-10">
            <%= image_tag @glass.image_url.url, :id =>'target', :size => '150x150', :align => 'left', :style => 'padding-top: 0px;' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :name, 'Select Image:', class:'control-label col-xs-2', :style => 'padding-top: 0px;'  %>
          <div class="col-xs-10">
            <%= f.file_field :image_url, :id =>'pictureInput' %>
          </div>
        </div>



        <div class="form-group">
          <div class="col-xs-12">
              <%= f.submit :class => "btn btn-default" %>    
              <%= link_to 'Back', glasses_path, :class => "btn btn-default" %>
            </div>
        </div>
    <% end %>


  </div>
</div>

app/views/glasses/edit.html.erb
<div class="title col-xs-12">
	<h1>Editing Glass <span><%= @glass.name%><span></h1>
</div>
<%= render 'form' %>

app/views/glasses/index.html.erb
<!-- p id="notice"><%= notice %></p-->

<div class="title col-xs-12">
  <h1>GLASSES</h1>
  <div class="col-xs-12 links">
    <%= link_to 'New Glass', new_glass_path%>
  </div>
  
</div>



<div class="col-xs-12">
    <div class="row">
      <% @glasses.each do |glass| %>
      <div class="col-xs-4">
        <h3> <%= glass.name %></h3>
        <p><%= link_to 'Show', glass_path(glass) %> - <%= link_to 'Edit', edit_glass_path(glass) %> - <%= link_to 'Delete', glass, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      </div>
      <% end %>
    </div>
</div>


<div class="pagination col-xs-12">
  <%= will_paginate(@glasses) %>
</div>

<%= form_tag glasses_path, :method => :get do %>
  <%= content_tag :label do %>
    Search name:
    <%= text_field_tag :q, params[:q] %>
    <%= hidden_field_tag :page, 1 %>
  <% end %>
<% end %>

app/views/glasses/new.html.erb
<div class="title col-xs-12">
	<h1>New Glass</h1>
</div>


<%= render 'form' %>

app/views/glasses/show.html.erb
<p id="notice"><%= notice %></p>

<div class="title col-xs-12">
  <h1>GLASS INFORMATION</h1>
</div>

<div class="col-xs-8">
	<table>
	  <tr>
	    <td><strong>Name:</strong></td>
	    <td style="padding-left: 20px;"><%= @glass.name %></td>
	  </tr>
	  <tr>
	    <td><strong>Image:</strong></td>
	    <td style="padding-left: 20px;"><%= image_tag @glass.image_url.url(:thumb) %></td>
	  </tr>
	</table>
	<%= link_to 'Edit', edit_glass_path(@glass) %> |
	<%= link_to 'Back', glasses_path %>
</div>