config/routes.rb
Rails.application.routes.draw do
  resources :lists
  resources :recipes
  resources :recipes_steps
  resources :ingredients
  resources :garnishes
  resources :categories
  resources :glasses

  resources :recipe_steps do
    post :sort, on: :collection
  end

  get 'sync' => 'sync#index'

  root to: 'visitors#index'
  devise_for :users
  resources :users

  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for "User", at: 'auth'
    end
  end

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sync' => 'sync#create'
      end
    end
  end

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_nav_links_maintenance.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Categories', categories_path %></li>
  <li><%= link_to 'Glasses', glasses_path %></li>
  <li><%= link_to 'Ingredients', ingredients_path  %></li>
  <li><%= link_to 'Recipes', recipes_path  %></li>
  <li><%= link_to 'Lists', lists_path  %></li>
<% end %>

app/views/layouts/_navigation.html.erb
          <div class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <span class="visible-xs navbar-brand"><%= link_to 'Home', root_path, class: 'navbar-brand' %></span>
            </div>
            <div class="navbar-collapse collapse sidebar-navbar-collapse">
              <ul class="nav navbar-nav" id="sidenav01">
                <%= render 'layouts/navigation_links' %>
                <% if user_signed_in? %>
                <li class="active">
                  
                  <a href="#" data-toggle="collapse" data-target="#toggleMaintenance" data-parent="#sidenav01" class="collapsed">
                    <span class="glyphicon glyphicon-inbox"></span> Maintenance <span class="caret "></span>
                  </a>
                  <div class="collapse" id="toggleMaintenance" style="height: 0px;">
                    <ul class="nav nav-list">
                      <%= render 'layouts/nav_links_maintenance' %>
                    </ul>
                  </div>
                </li>

                <li class="active">
                  <a href="#" data-toggle="collapse" data-target="#toggleUser3" data-parent="#sidenav01" class="collapsed">
                    <span class="glyphicon glyphicon-user"></span> User <span class="caret"></span>
                  </a>
                  <div class="collapse" id="toggleUser3" style="height: 0px;">
                    <ul class="nav nav-list">
                      <%= render 'layouts/nav_links_for_auth' %>
                    </ul>
                  </div>
                </li>
                <% else %>
                <li><%= link_to ' Sign in', new_user_session_path, :class=>'glyphicon glyphicon-user' %></li>
                <% end %>
                
              </ul>
            </div><!--/.nav-collapse -->
          </div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li style="width: 100%; height: 175px;">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<%= link_to image_tag('logo.png', width:'150'), root_path, :style=>'width 100%; height: 175px;', :class=>'img-responsive'%>
	</div>
</li>
<li>
	<%= link_to ' Home', root_path, :class=>'glyphicon glyphicon-home' %>
</li>
<li>
	<%= link_to ' About', page_path('about'), :class=>'glyphicon glyphicon-info-sign' %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Liquor Cabinet" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Liquor Cabinet" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="row-fluid" style="height:100%;">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="padding:0;height:100%">
        <div class="col-sm-3 col-md-2 col-lg-2" style="padding:0;height:100%;">
          <div class="sidebar-nav">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
        <div class="col-sm-9 col-md-10 col-lg-10" style="background-color:#f8f8f8;padding:0;min-height:100%">
            <%= render 'layouts/messages' %>
            <%= yield %>
        </div>
      </div>

    </div>

  </body>
</html>